services:
  # Grafana service
  # grafana:
  #   image: grafana/grafana:latest
  #   ports:
  #     - '3200:3000' # Expose Grafana's default port to your local machine
  #   volumes:
  #     - grafana-data:/var/lib/grafana
  #   networks:
  #     - monitoring
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin # Optional: Set admin password for Grafana

  # # Loki service
  # loki:
  #   image: grafana/loki:latest
  #   ports:
  #     - '3100:3100' # Expose Loki's default port to your local machine
  #   volumes:
  #     - loki-data:/data
  #   networks:
  #     - monitoring
  #   environment:
  #     - LOKI_STORAGE_PATH=/data/loki

  # Your app service
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
  reverse-proxy:
    image: traefik:v3.3
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesResolvers.myresolver.acme.tlsChallenge=true"
      - "--certificatesResolvers.myresolver.acme.email=szankdav@svenbot.cloud"
      - "--certificatesResolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
  sven:
    image: ghcr.io/szankdav/sven:latest # Specify the build directory for your app or use an image
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sven.rule=Host(`svenbot.cloud`)"
      - "traefik.http.routers.sven.entrypoints=websecure"
      - "traefik.http.routers.sven.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      mode: replicated
      replicas: 3
    # networks:
    #   - monitoring
    # environment:
    #   - LOKI_URL=http://loki:3100 # Pointing your app to Loki service within the Docker network
    # depends_on:
    #   - loki
    #   - grafana
    env_file:
      - .env
    # Other environment variables for your app can be defined here

# Define the shared network
# networks:
#   monitoring:
#     driver: bridge

# # Volumes to persist Grafana and Loki data
volumes:
  letsencrypt:
#   grafana-data:
#   loki-data:
