FROM node:22.13.0-bullseye

WORKDIR /sven

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

RUN npx playwright install --with-deps

EXPOSE 3000

CMD npm run start & npm run wait && npm run playwright-prod