import dotenv from 'dotenv';
import { logger } from './winston/winston.js';

dotenv.config();

const {
  DISCORD_TOKEN_SVEN_DEV,
  DISCORD_TOKEN_FAENDAL_DEV,
  DISCORD_CLIENT_SVEN_ID_DEV,
  DISCORD_CLIENT_FAENDAL_ID_DEV,
  GUILD_ID_DEV, DB_PATH,
  DISCORD_CLIENT_SVEN_DEV_SECRET,
  SZANKDAV_ID,
  DEVBOT_CIKKEK_CHANNEL,
  DEVBOT_HIREK_CHANNEL
} =
  process.env;

if (!DISCORD_TOKEN_SVEN_DEV || !DISCORD_TOKEN_FAENDAL_DEV || !DISCORD_CLIENT_SVEN_ID_DEV || !DISCORD_CLIENT_FAENDAL_ID_DEV || !DISCORD_CLIENT_SVEN_DEV_SECRET || !GUILD_ID_DEV || !SZANKDAV_ID || !DEVBOT_CIKKEK_CHANNEL || !DEVBOT_HIREK_CHANNEL) {
  logger.error('Missing environment variables');
  throw new Error('Missing environment variables');
}

export const config = {
  DISCORD_TOKEN_SVEN_DEV,
  DISCORD_TOKEN_FAENDAL_DEV,
  DISCORD_CLIENT_SVEN_ID_DEV,
  DISCORD_CLIENT_FAENDAL_ID_DEV,
  DISCORD_CLIENT_SVEN_DEV_SECRET,
  GUILD_ID_DEV,
  DB_PATH,
  SZANKDAV_ID,
  DEVBOT_CIKKEK_CHANNEL,
  DEVBOT_HIREK_CHANNEL
};
